"""education_info

Revision ID: 2da8a2d8ac77
Revises: 6edfea10dae4
Create Date: 2019-02-15 12:32:04.492261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2da8a2d8ac77'
down_revision = '6edfea10dae4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('education_info',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('degree', sa.String(length=40), nullable=True),
    sa.Column('field_of_study', sa.String(length=120), nullable=True),
    sa.Column('institution', sa.String(length=120), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('year_of_degree', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('education_info')
    # ### end Alembic commands ###
