"""please please work please

Revision ID: 364b24ea48d1
Revises: 820a25664cc2
Create Date: 2019-02-27 15:09:00.122710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '364b24ea48d1'
down_revision = '820a25664cc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proposal', sa.Column('type_of_call', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proposal', 'type_of_call')
    # ### end Alembic commands ###
