"""empty message

Revision ID: 5922a8435b42
Revises: 364b24ea48d1
Create Date: 2019-02-27 18:58:51.621324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5922a8435b42'
down_revision = '364b24ea48d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proposal', sa.Column('call_status', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proposal', 'call_status')
    # ### end Alembic commands ###
