"""all tables

Revision ID: 820a25664cc2
Revises: 
Create Date: 2019-02-26 14:20:41.128445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '820a25664cc2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('access', sa.Integer(), nullable=True),
    sa.Column('about_me', sa.String(length=140), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('academic_collabs',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DATE(), nullable=True),
    sa.Column('end_date', sa.DATE(), nullable=True),
    sa.Column('institution', sa.String(length=50), nullable=True),
    sa.Column('department', sa.String(length=40), nullable=True),
    sa.Column('location', sa.String(length=30), nullable=True),
    sa.Column('collaborator', sa.String(length=40), nullable=True),
    sa.Column('collaborator_goal', sa.String(length=50), nullable=True),
    sa.Column('interaction_freq', sa.String(length=20), nullable=True),
    sa.Column('primary_attribution', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('application',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('communications',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('number_lectures', sa.Integer(), nullable=True),
    sa.Column('number_visits', sa.Integer(), nullable=True),
    sa.Column('number_media', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conference',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DATE(), nullable=True),
    sa.Column('end_date', sa.DATE(), nullable=True),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('event_type', sa.String(length=40), nullable=True),
    sa.Column('role', sa.String(length=40), nullable=True),
    sa.Column('location', sa.String(length=30), nullable=True),
    sa.Column('primary_attribution', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('distinctions_and_awards',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.String(length=4), nullable=True),
    sa.Column('awarding_body', sa.String(length=60), nullable=True),
    sa.Column('award_details', sa.String(length=120), nullable=True),
    sa.Column('member_name', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('education_info',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('degree', sa.String(length=40), nullable=True),
    sa.Column('field_of_study', sa.String(length=120), nullable=True),
    sa.Column('institution', sa.String(length=120), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('year_of_degree', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employment',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution', sa.String(length=60), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('years', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('funding_diversification',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.String(length=12), nullable=True),
    sa.Column('end_date', sa.String(length=12), nullable=True),
    sa.Column('funding_amt', sa.Integer(), nullable=True),
    sa.Column('funding_body', sa.String(length=60), nullable=True),
    sa.Column('funding_program', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('funding_ratio',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('annual_spend', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('impacts',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=60), nullable=True),
    sa.Column('category', sa.String(length=40), nullable=True),
    sa.Column('primary_beneficiary', sa.String(length=40), nullable=True),
    sa.Column('primary_attribution', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('innovation',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('innovation_type', sa.String(length=40), nullable=True),
    sa.Column('title', sa.String(length=60), nullable=True),
    sa.Column('primary_attribution', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('non_academic_collabs',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DATE(), nullable=True),
    sa.Column('end_date', sa.DATE(), nullable=True),
    sa.Column('institution', sa.String(length=50), nullable=True),
    sa.Column('department', sa.String(length=40), nullable=True),
    sa.Column('location', sa.String(length=30), nullable=True),
    sa.Column('collaborator', sa.String(length=40), nullable=True),
    sa.Column('collaborator_goal', sa.String(length=50), nullable=True),
    sa.Column('interaction_freq', sa.String(length=20), nullable=True),
    sa.Column('primary_attribution', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('presentation',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=40), nullable=True),
    sa.Column('title', sa.String(length=60), nullable=True),
    sa.Column('primary_attribution', sa.String(length=40), nullable=True),
    sa.Column('organising_body', sa.String(length=40), nullable=True),
    sa.Column('location', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('professional_studies',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.String(length=12), nullable=True),
    sa.Column('end_date', sa.String(length=12), nullable=True),
    sa.Column('society_name', sa.String(length=40), nullable=True),
    sa.Column('member_type', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proposal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('deadline', sa.DATE(), nullable=True),
    sa.Column('text_of_call', sa.String(length=500), nullable=True),
    sa.Column('target_audience', sa.String(length=50), nullable=True),
    sa.Column('eligibility_criteria', sa.String(length=100), nullable=True),
    sa.Column('reporting_guidelines', sa.String(length=150), nullable=True),
    sa.Column('start_date', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proposal_timestamp'), 'proposal', ['timestamp'], unique=False)
    op.create_table('public_engagement',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DATE(), nullable=True),
    sa.Column('end_date', sa.DATE(), nullable=True),
    sa.Column('topic', sa.String(length=50), nullable=True),
    sa.Column('activity_type', sa.String(length=40), nullable=True),
    sa.Column('target_area', sa.String(length=20), nullable=True),
    sa.Column('primary_attribution', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('publication',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('publication_type', sa.String(length=40), nullable=True),
    sa.Column('title', sa.String(length=60), nullable=True),
    sa.Column('primary_attribution', sa.String(length=40), nullable=True),
    sa.Column('journal_name', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('doi', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_members',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.Column('position_in_team', sa.String(length=120), nullable=True),
    sa.Column('other_users', sa.String(length=120), nullable=True),
    sa.Column('start_date', sa.String(length=12), nullable=True),
    sa.Column('end_date', sa.String(length=12), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_members')
    op.drop_table('publication')
    op.drop_table('public_engagement')
    op.drop_index(op.f('ix_proposal_timestamp'), table_name='proposal')
    op.drop_table('proposal')
    op.drop_table('professional_studies')
    op.drop_table('presentation')
    op.drop_table('non_academic_collabs')
    op.drop_table('innovation')
    op.drop_table('impacts')
    op.drop_table('funding_ratio')
    op.drop_table('funding_diversification')
    op.drop_table('employment')
    op.drop_table('education_info')
    op.drop_table('distinctions_and_awards')
    op.drop_table('conference')
    op.drop_table('communications')
    op.drop_table('application')
    op.drop_table('academic_collabs')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
